### ISSUE TITLE
Suggestion: make a release and attach binaries

### ISSUE THREAD

**Issue by sbrl** [metala/tarpit#1]
I don't have a Go compiler toolchain installed (and the Go compiler is pretty huge the last time I checked), so it would be cool if there was a release with attached binaries that I could use.

**Comment by metala** [comment]
I see. That might be ok, but I don't really want to take care of the distribution part. It puts extra effort to sign executables for different platforms and publish them somewhere (e.g. GitHub). That's why I have setup an automatic docker build and if you trust GitHub and Docker, then you will trust the built image.

I am not sure if the current implementation is good enough. It doesn't make sense to have 25% CPU usage for a program that is just passing data to `/dev/null` and sending a ping once in a while. I am considering debug the code and check if it's GC-related issue or just rewrite the whole thing in C or maybe even try Rust.

Moreover, tarpits sound cool, but are not as good as I thought, because:
1. Most of the clients that are connecting to those ports I believe are montoring clients from my cloud providers.
2. A lot of the SSH scanners I try to slow down are staying for no more than a minute. (Don't have stats, just some observations from an experiment a few months ago)
3. It's probably better, if you honeypot the attackers and waste their time inside a sandbox.

**Comment by sbrl** [comment]
Ah, I see. Those are some interesting observations - and I didn't realise that it took up so much CPU.

I don't use Docker at the moment, so such a container isn't really useful to me.

It would be interesting to do some more extensive tests on tarpits to see what effect they have over a longer period of time. Your suggestion of a honeypot does sound like an interesting idea though too.

**Comment by metala** [comment]
@sbrl  I have set up an automated building of executables and now you can grab them from the releases tab.

In addition to that, I have fixed the issue with the high CPU load. It was a silly mistake and I probably didn't read the documentation for `time.Tick()`.

**Comment by metala** [comment]
I will just close the issue, since there are now binaries available in the release section.
